# Splunk Universal Forwarder inputs.conf — DC01 and WS01
# Placed in: C:\Program Files\SplunkUniversalForwarder\etc\system\local\
# Service must run as Local System to read the Security log.

[WinEventLog://Security]
index = winlogs

[WinEventLog://System]
index = winlogs

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = winlogs

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = winlogs
